package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateController génère le fichier contrôleur
func (g *Generator) GenerateController() error {
	modelName := g.Schema.Model
	filename := filepath.Join("app", "controllers", toSnakeCase(modelName)+"_controller.go")

	// Créer le répertoire s'il n'existe pas
	if err := os.MkdirAll(filepath.Dir(filename), 0755); err != nil {
		return err
	}

	content := g.generateControllerContent()
	return os.WriteFile(filename, []byte(content), 0644)
}

func (g *Generator) generateControllerContent() string {
	var sb strings.Builder
	modelName := g.Schema.Model
	controllerName := modelName + "Controller"
	varName := toCamelCase(modelName)

	sb.WriteString("package controllers\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"net/http\"\n")
	sb.WriteString("\t\"strconv\"\n\n")
	sb.WriteString("\t\"app/models\"\n")
	sb.WriteString("\t\"app/repositories\"\n")
	sb.WriteString("\t\"app/requests\"\n\n")
	sb.WriteString("\t\"github.com/gin-gonic/gin\"\n")
	sb.WriteString("\t\"github.com/go-playground/validator/v10\"\n")
	sb.WriteString(")\n\n")

	// Structure du contrôleur
	sb.WriteString(fmt.Sprintf("// %s gère les requêtes HTTP pour %s\n", controllerName, modelName))
	sb.WriteString(fmt.Sprintf("type %s struct {\n", controllerName))
	sb.WriteString(fmt.Sprintf("\trepo repositories.%sInterface\n", modelName))
	sb.WriteString("\tvalidate *validator.Validate\n")
	sb.WriteString("}\n\n")

	// Constructeur
	sb.WriteString(fmt.Sprintf("// New%s crée une nouvelle instance du contrôleur\n", controllerName))
	sb.WriteString(fmt.Sprintf("func New%s() *%s {\n", controllerName, controllerName))
	sb.WriteString(fmt.Sprintf("\treturn &%s{\n", controllerName))
	sb.WriteString(fmt.Sprintf("\t\trepo: repositories.New%sRepository(),\n", modelName))
	sb.WriteString("\t\tvalidate: validator.New(),\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	// Méthode Index (List)
	sb.WriteString(fmt.Sprintf("// Index récupère la liste des %ss\n", varName))
	sb.WriteString(fmt.Sprintf("// @Summary Liste des %ss\n", varName))
	sb.WriteString("// @Description Récupère tous les " + varName + "s avec pagination\n")
	sb.WriteString("// @Tags " + modelName + "\n")
	sb.WriteString("// @Accept json\n")
	sb.WriteString("// @Produce json\n")
	sb.WriteString("// @Param page query int false \"Numéro de page\" default(1)\n")
	sb.WriteString("// @Param page_size query int false \"Taille de page\" default(10)\n")
	sb.WriteString(fmt.Sprintf("// @Success 200 {object} map[string]interface{}\n"))
	sb.WriteString("// @Router /" + toSnakeCase(modelName) + "s [get]\n")
	sb.WriteString(fmt.Sprintf("func (ctrl *%s) Index(c *gin.Context) {\n", controllerName))
	sb.WriteString("\t// Paramètres de pagination\n")
	sb.WriteString("\tpage, _ := strconv.Atoi(c.DefaultQuery(\"page\", \"1\"))\n")
	sb.WriteString("\tpageSize, _ := strconv.Atoi(c.DefaultQuery(\"page_size\", \"10\"))\n\n")
	sb.WriteString("\tif page < 1 {\n")
	sb.WriteString("\t\tpage = 1\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\tif pageSize < 1 || pageSize > 100 {\n")
	sb.WriteString("\t\tpageSize = 10\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString(fmt.Sprintf("\t%ss, total, err := ctrl.repo.FindAll(page, pageSize)\n", varName))
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString("\t\tc.JSON(http.StatusInternalServerError, gin.H{\n")
	sb.WriteString("\t\t\t\"error\": \"Erreur lors de la récupération des données\",\n")
	sb.WriteString("\t\t})\n")
	sb.WriteString("\t\treturn\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString("\tc.JSON(http.StatusOK, gin.H{\n")
	sb.WriteString(fmt.Sprintf("\t\t\"data\": %ss,\n", varName))
	sb.WriteString("\t\t\"pagination\": gin.H{\n")
	sb.WriteString("\t\t\t\"page\": page,\n")
	sb.WriteString("\t\t\t\"page_size\": pageSize,\n")
	sb.WriteString("\t\t\t\"total\": total,\n")
	sb.WriteString("\t\t\t\"total_pages\": (total + int64(pageSize) - 1) / int64(pageSize),\n")
	sb.WriteString("\t\t},\n")
	sb.WriteString("\t})\n")
	sb.WriteString("}\n\n")

	// Méthode Show (Get by ID)
	sb.WriteString(fmt.Sprintf("// Show récupère un %s par ID\n", varName))
	sb.WriteString(fmt.Sprintf("// @Summary Afficher un %s\n", varName))
	sb.WriteString("// @Description Récupère un " + varName + " spécifique par son ID\n")
	sb.WriteString("// @Tags " + modelName + "\n")
	sb.WriteString("// @Accept json\n")
	sb.WriteString("// @Produce json\n")
	sb.WriteString("// @Param id path string true \"ID du " + varName + "\"\n")
	sb.WriteString(fmt.Sprintf("// @Success 200 {object} models.%s\n", modelName))
	sb.WriteString("// @Router /" + toSnakeCase(modelName) + "s/{id} [get]\n")
	sb.WriteString(fmt.Sprintf("func (ctrl *%s) Show(c *gin.Context) {\n", controllerName))
	sb.WriteString("\tid := c.Param(\"id\")\n\n")
	sb.WriteString(fmt.Sprintf("\t%s, err := ctrl.repo.FindByID(id)\n", varName))
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString("\t\tc.JSON(http.StatusNotFound, gin.H{\n")
	sb.WriteString("\t\t\t\"error\": \"Enregistrement non trouvé\",\n")
	sb.WriteString("\t\t})\n")
	sb.WriteString("\t\treturn\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString(fmt.Sprintf("\tc.JSON(http.StatusOK, %s)\n", varName))
	sb.WriteString("}\n\n")

	// Méthode Store (Create)
	sb.WriteString(fmt.Sprintf("// Store crée un nouveau %s\n", varName))
	sb.WriteString(fmt.Sprintf("// @Summary Créer un %s\n", varName))
	sb.WriteString("// @Description Crée un nouveau " + varName + "\n")
	sb.WriteString("// @Tags " + modelName + "\n")
	sb.WriteString("// @Accept json\n")
	sb.WriteString("// @Produce json\n")
	sb.WriteString(fmt.Sprintf("// @Param %s body requests.Create%sRequest true \"Données du %s\"\n", 
		varName, modelName, varName))
	sb.WriteString(fmt.Sprintf("// @Success 201 {object} models.%s\n", modelName))
	sb.WriteString("// @Router /" + toSnakeCase(modelName) + "s [post]\n")
	sb.WriteString(fmt.Sprintf("func (ctrl *%s) Store(c *gin.Context) {\n", controllerName))
	sb.WriteString(fmt.Sprintf("\tvar req requests.Create%sRequest\n\n", modelName))
	sb.WriteString("\tif err := c.ShouldBindJSON(&req); err != nil {\n")
	sb.WriteString("\t\tc.JSON(http.StatusBadRequest, gin.H{\n")
	sb.WriteString("\t\t\t\"error\": \"Données invalides\",\n")
	sb.WriteString("\t\t\t\"details\": err.Error(),\n")
	sb.WriteString("\t\t})\n")
	sb.WriteString("\t\treturn\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString("\tif err := ctrl.validate.Struct(req); err != nil {\n")
	sb.WriteString("\t\tc.JSON(http.StatusBadRequest, gin.H{\n")
	sb.WriteString("\t\t\t\"error\": \"Validation échouée\",\n")
	sb.WriteString("\t\t\t\"details\": err.Error(),\n")
	sb.WriteString("\t\t})\n")
	sb.WriteString("\t\treturn\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString(fmt.Sprintf("\t%s := req.ToModel()\n\n", varName))
	sb.WriteString(fmt.Sprintf("\tif err := ctrl.repo.Create(&%s); err != nil {\n", varName))
	sb.WriteString("\t\tc.JSON(http.StatusInternalServerError, gin.H{\n")
	sb.WriteString("\t\t\t\"error\": \"Erreur lors de la création\",\n")
	sb.WriteString("\t\t})\n")
	sb.WriteString("\t\treturn\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString(fmt.Sprintf("\tc.JSON(http.StatusCreated, %s)\n", varName))
	sb.WriteString("}\n\n")

	// Méthode Update
	sb.WriteString(fmt.Sprintf("// Update met à jour un %s\n", varName))
	sb.WriteString(fmt.Sprintf("// @Summary Mettre à jour un %s\n", varName))
	sb.WriteString("// @Description Met à jour un " + varName + " existant\n")
	sb.WriteString("// @Tags " + modelName + "\n")
	sb.WriteString("// @Accept json\n")
	sb.WriteString("// @Produce json\n")
	sb.WriteString("// @Param id path string true \"ID du " + varName + "\"\n")
	sb.WriteString(fmt.Sprintf("// @Param %s body requests.Update%sRequest true \"Nouvelles données\"\n", 
		varName, modelName))
	sb.WriteString(fmt.Sprintf("// @Success 200 {object} models.%s\n", modelName))
	sb.WriteString("// @Router /" + toSnakeCase(modelName) + "s/{id} [put]\n")
	sb.WriteString(fmt.Sprintf("func (ctrl *%s) Update(c *gin.Context) {\n", controllerName))
	sb.WriteString("\tid := c.Param(\"id\")\n\n")
	sb.WriteString(fmt.Sprintf("\t%s, err := ctrl.repo.FindByID(id)\n", varName))
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString("\t\tc.JSON(http.StatusNotFound, gin.H{\n")
	sb.WriteString("\t\t\t\"error\": \"Enregistrement non trouvé\",\n")
	sb.WriteString("\t\t})\n")
	sb.WriteString("\t\treturn\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString(fmt.Sprintf("\tvar req requests.Update%sRequest\n\n", modelName))
	sb.WriteString("\tif err := c.ShouldBindJSON(&req); err != nil {\n")
	sb.WriteString("\t\tc.JSON(http.StatusBadRequest, gin.H{\n")
	sb.WriteString("\t\t\t\"error\": \"Données invalides\",\n")
	sb.WriteString("\t\t\t\"details\": err.Error(),\n")
	sb.WriteString("\t\t})\n")
	sb.WriteString("\t\treturn\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString("\tif err := ctrl.validate.Struct(req); err != nil {\n")
	sb.WriteString("\t\tc.JSON(http.StatusBadRequest, gin.H{\n")
	sb.WriteString("\t\t\t\"error\": \"Validation échouée\",\n")
	sb.WriteString("\t\t\t\"details\": err.Error(),\n")
	sb.WriteString("\t\t})\n")
	sb.WriteString("\t\treturn\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString(fmt.Sprintf("\treq.UpdateModel(%s)\n\n", varName))
	sb.WriteString(fmt.Sprintf("\tif err := ctrl.repo.Update(%s); err != nil {\n", varName))
	sb.WriteString("\t\tc.JSON(http.StatusInternalServerError, gin.H{\n")
	sb.WriteString("\t\t\t\"error\": \"Erreur lors de la mise à jour\",\n")
	sb.WriteString("\t\t})\n")
	sb.WriteString("\t\treturn\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString(fmt.Sprintf("\tc.JSON(http.StatusOK, %s)\n", varName))
	sb.WriteString("}\n\n")

	// Méthode Delete
	sb.WriteString(fmt.Sprintf("// Delete supprime un %s\n", varName))
	sb.WriteString(fmt.Sprintf("// @Summary Supprimer un %s\n", varName))
	sb.WriteString("// @Description Supprime un " + varName + " par son ID\n")
	sb.WriteString("// @Tags " + modelName + "\n")
	sb.WriteString("// @Accept json\n")
	sb.WriteString("// @Produce json\n")
	sb.WriteString("// @Param id path string true \"ID du " + varName + "\"\n")
	sb.WriteString("// @Success 204\n")
	sb.WriteString("// @Router /" + toSnakeCase(modelName) + "s/{id} [delete]\n")
	sb.WriteString(fmt.Sprintf("func (ctrl *%s) Delete(c *gin.Context) {\n", controllerName))
	sb.WriteString("\tid := c.Param(\"id\")\n\n")
	sb.WriteString("\tif err := ctrl.repo.Delete(id); err != nil {\n")
	sb.WriteString("\t\tc.JSON(http.StatusInternalServerError, gin.H{\n")
	sb.WriteString("\t\t\t\"error\": \"Erreur lors de la suppression\",\n")
	sb.WriteString("\t\t})\n")
	sb.WriteString("\t\treturn\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString("\tc.Status(http.StatusNoContent)\n")
	sb.WriteString("}\n")

	return sb.String()
}
